import type { AppState } from './types';

export const initialAppState: AppState = {
  currentUser: null,
  users: [
    {
      id: 'client-jan',
      role: 'client',
      name: 'Jan Kowalski',
      email: 'jan.kowalski@example.com',
    },
    {
      id: 'courier-marek',
      role: 'courier',
      name: 'Marek Nowak',
      email: 'marek.nowak@example.com',
    },
    {
      id: 'point-warsaw',
      role: 'point',
      name: 'Punkt Warszawa Centrum',
      email: 'warszawa.centrum@pingwinpost.pl',
      location: 'ul. Marszałkowska 104, 00-017 Warszawa',
    },
    {
      id: 'admin-anna',
      role: 'admin',
      name: 'Anna Zielińska',
      email: 'admin@pingwinpost.pl',
    },
  ],
  points: [
    {
      id: 'point-warsaw',
      name: 'PingwinPost - Warszawa Centrum',
      type: 'Punkt odbioru',
      address: 'ul. Marszałkowska 104, 00-017 Warszawa',
      hours: 'Pn-Pt: 8:00-20:00, Sb: 9:00-15:00',
      phone: '+48 22 123 4567',
    },
    {
      id: 'locker-waw01',
      name: 'Paczkomat WAW01',
      type: 'Paczkomat',
      address: 'ul. Złota 44, 00-120 Warszawa',
      hours: '24/7',
      phone: '-',
    },
    {
      id: 'point-krakow',
      name: 'PingwinPost - Kraków Stare Miasto',
      type: 'Punkt odbioru',
      address: 'ul. Floriańska 15, 31-019 Kraków',
      hours: 'Pn-Pt: 9:00-19:00, Sb: 10:00-14:00',
      phone: '+48 12 345 6789',
    },
    {
      id: 'locker-krk12',
      name: 'Paczkomat KRK12',
      type: 'Paczkomat',
      address: 'ul. Długa 72, 31-147 Kraków',
      hours: '24/7',
      phone: '-',
    },
    {
      id: 'point-wroclaw',
      name: 'PingwinPost - Wrocław Rynek',
      type: 'Punkt odbioru',
      address: 'Rynek 8, 50-106 Wrocław',
      hours: 'Pn-Pt: 8:00-20:00, Sb-Nd: 10:00-18:00',
      phone: '+48 71 234 5678',
    },
  ],
  shipments: [
    {
      id: 'PW123456789PL',
      clientId: 'client-jan',
      pointId: 'point-warsaw',
      assignedCourierId: 'courier-marek',
      status: 'W transporcie',
      created: '24.03.2026 16:45',
      estimatedDelivery: '26.03.2026',
      sender: {
        name: 'Jan Kowalski',
        phone: '+48 123 456 789',
        address: 'ul. Marszałkowska 1, 00-017 Warszawa',
      },
      recipient: {
        name: 'Anna Nowak',
        phone: '+48 987 654 321',
        address: 'ul. Floriańska 15, 31-019 Kraków',
      },
      package: {
        type: 'Paczka standardowa',
        weight: '2.5 kg',
        dimensions: '30 x 20 x 15 cm',
        value: '250 PLN',
        contents: 'Akcesoria biurowe',
      },
      payment: {
        status: 'Opłacona',
        method: 'Karta płatnicza',
        amount: '24.99 PLN',
        date: '24.03.2026 18:20',
      },
      history: [
        {
          date: '25.03.2026 14:30',
          location: 'Katowice - Sortownia',
          status: 'W transporcie',
          description: 'Przesyłka w drodze',
        },
        {
          date: '25.03.2026 09:15',
          location: 'Warszawa - Punkt nadania',
          status: 'Nadana',
          description: 'Przesyłka nadana',
        },
        {
          date: '24.03.2026 18:20',
          location: 'Warszawa - Magazyn',
          status: 'Opłacona',
          description: 'Przesyłka opłacona',
        },
        {
          date: '24.03.2026 16:45',
          location: 'Online',
          status: 'Utworzona',
          description: 'Przesyłka utworzona',
        },
      ],
    },
    {
      id: 'PW987654321PL',
      clientId: 'client-jan',
      pointId: 'point-warsaw',
      assignedCourierId: 'courier-marek',
      status: 'Oczekuje na odbiór',
      created: '23.03.2026 10:20',
      estimatedDelivery: '25.03.2026',
      sender: {
        name: 'Jan Kowalski',
        phone: '+48 123 456 789',
        address: 'ul. Marszałkowska 1, 00-017 Warszawa',
      },
      recipient: {
        name: 'Piotr Wiśniewski',
        phone: '+48 555 222 111',
        address: 'ul. Grójecka 91, 02-101 Warszawa',
      },
      package: {
        type: 'Paczka standardowa',
        weight: '1.1 kg',
        dimensions: '25 x 15 x 10 cm',
        value: '129 PLN',
        contents: 'Elektronika',
      },
      payment: {
        status: 'Opłacona',
        method: 'Przelew online',
        amount: '21.99 PLN',
        date: '23.03.2026 10:35',
      },
      history: [
        {
          date: '25.03.2026 08:10',
          location: 'Warszawa - Punkt odbioru',
          status: 'Oczekuje na odbiór',
          description: 'Przesyłka czeka na odbiór',
        },
        {
          date: '24.03.2026 19:00',
          location: 'Warszawa - Kurier',
          status: 'Wydana kurierowi',
          description: 'Przesyłka wydana do doręczenia',
        },
      ],
    },
    {
      id: 'PW555444333PL',
      clientId: 'client-jan',
      pointId: 'point-warsaw',
      assignedCourierId: 'courier-marek',
      status: 'Nadana',
      created: '25.03.2026 11:20',
      estimatedDelivery: '27.03.2026',
      sender: {
        name: 'Jan Kowalski',
        phone: '+48 123 456 789',
        address: 'ul. Marszałkowska 1, 00-017 Warszawa',
      },
      recipient: {
        name: 'Maria Kowalczyk',
        phone: '+48 111 222 333',
        address: 'ul. Długa 72, 50-001 Wrocław',
      },
      package: {
        type: 'Paczka standardowa',
        weight: '3.2 kg',
        dimensions: '40 x 30 x 15 cm',
        value: '310 PLN',
        contents: 'Artykuły domowe',
      },
      payment: {
        status: 'Offline — do potwierdzenia',
        method: 'Płatność w punkcie',
        amount: '26.99 PLN',
        date: '25.03.2026 11:20',
      },
      history: [
        {
          date: '25.03.2026 11:20',
          location: 'Warszawa - Punkt nadania',
          status: 'Nadana',
          description: 'Przesyłka przyjęta w punkcie',
        },
      ],
    },
    {
      id: 'PW111222333PL',
      clientId: 'client-jan',
      pointId: 'point-krakow',
      assignedCourierId: 'courier-marek',
      status: 'Doręczona',
      created: '20.03.2026 09:15',
      estimatedDelivery: '22.03.2026',
      sender: {
        name: 'Jan Kowalski',
        phone: '+48 123 456 789',
        address: 'ul. Marszałkowska 1, 00-017 Warszawa',
      },
      recipient: {
        name: 'Tomasz Lewandowski',
        phone: '+48 444 555 666',
        address: 'ul. Świdnicka 53, 50-030 Wrocław',
      },
      package: {
        type: 'Paczka ekspresowa',
        weight: '0.8 kg',
        dimensions: '20 x 15 x 8 cm',
        value: '89 PLN',
        contents: 'Dokumenty',
      },
      payment: {
        status: 'Opłacona',
        method: 'Karta płatnicza',
        amount: '29.99 PLN',
        date: '20.03.2026 09:18',
      },
      history: [
        {
          date: '22.03.2026 13:00',
          location: 'Wrocław',
          status: 'Doręczona',
          description: 'Przesyłka doręczona do odbiorcy',
        },
      ],
    },
  ],
  claims: [
    {
      id: 'REK001',
      shipmentId: 'PW123456789PL',
      clientId: 'client-jan',
      subject: 'Opóźnienie przesyłki',
      description: 'Przesyłka nie dotarła w przewidywanym terminie.',
      status: 'W trakcie',
      created: '26.03.2026 10:30',
    },
    {
      id: 'REK002',
      shipmentId: 'PW111222333PL',
      clientId: 'client-jan',
      subject: 'Uszkodzone opakowanie',
      description: 'Paczka została dostarczona z uszkodzonym kartonem.',
      status: 'Rozwiązana',
      created: '23.03.2026 17:40',
    },
  ],
};
