package org.example.pocztabackend.model.enums;

public enum ShipmentRouteStatus {
    READY_FOR_HANDOVER,
    ACCEPTED_AT_SOURCE,
    IN_TRANSIT_TO_ORIGIN_HUB,
    AT_ORIGIN_HUB,
    IN_TRANSIT_TO_DESTINATION_HUB,
    AT_DESTINATION_HUB,
    OUT_FOR_DELIVERY,
    IN_TRANSIT_TO_TARGET_POINT,
    AWAITING_PICKUP,
    IN_TRANSIT_TO_TARGET_LOCKER,
    AWAITING_LOCKER_PICKUP,
    DELIVERY_ATTEMPT_FAILED,
    RETURN_IN_TRANSIT,
    RETURNED,
    DELIVERED,
    CANCELED
}
