spring.application.name=poczta-backend
server.port=8081

# Poprawne dane do bazy w Dockerze
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/XEPDB1
spring.datasource.username=springuser
spring.datasource.password=spring
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Ustawienia Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
