spring.application.name=poczta-backend

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=SYSTEM
spring.datasource.password=TWOJE_HASLO_Z_INSTALACJI
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# To automatycznie stworzy tabele w Oracle na podstawie Twoich klas Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect